const actionType = {
  ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE: "ADD_CARD_FAILURE",
  EDIT_CARD_SUCCESS: "EDIT_CARD_SUCCESS",
  EDIT_CARD_FAILURE: "EDIT_CARD_FAILURE",
  GET_CARD_SUCCESS: "GET_CARD_SUCCESS",
  GET_CARD_FAILURE: "GET_CARD_FAILURE",
  DELETE_CARD_SUCCESS: "DELETE_CARD_SUCCESS",
  DELETE_CARD_FAILURE: "DELETE_CARD_FAILURE"
};
export default actionType