const actionType = {
    PACKAGE_SEARCH_SUCCESS: "PACKAGE_SEARCH_SUCCESS",
    PACKAGE_SEARCH_FAILURE: "PACKAGE_SEARCH_FAILURE",
    
    
    PACKAGE_INFO_REQUEST: "PACKAGE_INFO_REQUEST",
    PACKAGE_INFO_SUCCESS: "PACKAGE_INFO_SUCCESS",
    PACKAGE_INFO_FAILURE: "PACKAGE_INFO_FAILURE",

    PACKAGE_PRICE_REQUEST: "PACKAGE_PRICE_REQUEST",
    PACKAGE_PRICE_SUCCESS: "PACKAGE_PRICE_SUCCESS",
    PACKAGE_PRICE_FAILURE: "PACKAGE_PRICE_FAILURE",

    PACKAGE_CALENDER_REQUEST: "PACKAGE_CALENDER_REQUEST",
    PACKAGE_CALENDER_SUCCESS: "PACKAGE_CALENDER_SUCCESS",
    PACKAGE_CALENDER_FAILURE: "PACKAGE_CALENDER_FAILURE",

    PACKAGE_FILTER_SUCCESS: "PACKAGE_FILTER_SUCCESS",
    PACKAGE_FILTER_FAILURE: "PACKAGE_FILTER_FAILURE",

    PACKAGE_MYTRIP_SUCCESS: "PACKAGE_MYTRIP_SUCCESS",
    PACKAGE_MYTRIP_FAILURE: "PACKAGE_MYTRIP_FAILURE",

    PACKAGE_BOOKING_STATUS_SUCCESS: "PACKAGE_BOOKING_STATUS_SUCCESS",
    PACKAGE_BOOKING_STATUS_FAILURE: "PACKAGE_BOOKING_STATUS_FAILURE",

    PACKAGE_BOOKING_SUCCESS: "PACKAGE_BOOKING_SUCCESS",
    PACKAGE_BOOKING_FAILURE: "PACKAGE_BOOKING_FAILURE",

    PACKAGE_PAYLOAD_SUCCESS: "PACKAGE_PAYLOAD_SUCCESS",

    PACKAGE_LIST_HOTEL_REQUEST: "PACKAGE_LIST_HOTEL_REQUEST",
    PACKAGE_LIST_HOTEL_SUCCESS: "PACKAGE_LIST_HOTEL_SUCCESS",
    PACKAGE_LIST_HOTEL_FAILURE: "PACKAGE_LIST_HOTEL_FAILURE",
    PACKAGE_BOOKING_CANCELLED_SUCCESSFULLY: "PACKAGE_BOOKING_CANCELLED_SUCCESSFULLY",
    PACKAGE_BOOKING_CANCELLED_FAILURE: "PACKAGE_BOOKING_CANCELLED_FAILURE",
    PACKAGE_GET_CATEGORY_SUCCESS: "PACKAGE_GET_CATEGORY_SUCCESS",
    PACKAGE_GET_CATEGORY_FAILURE: "PACKAGE_GET_CATEGORY_FAILURE",
    PACKAGE_GET_INTEREST_SUCCESS: "PACKAGE_GET_INTEREST_SUCCESS",
    PACKAGE_GET_INTEREST_FAILURE: "PACKAGE_GET_INTEREST_FAILURE",
    PACKAGE_GET_CANCEL_SUCCESS: "PACKAGE_GET_CANCEL_SUCCESS",
    PACKAGE_GET_CANCEL_FAILURE: "PACKAGE_GET_CANCEL_FAILURE",
    PACKAGE_GET_LOCATIONS_REQUEST: "PACKAGE_GET_LOCATIONS_REQUEST",
    PACKAGE_GET_LOCATIONS_SUCCESS: "PACKAGE_GET_LOCATIONS_SUCCESS",
    PACKAGE_GET_LOCATIONS_FAILURE: "PACKAGE_GET_LOCATIONS_FAILURE",

};
export default actionType;