const actionType = {
  TRANSFER_SEARCH_REQUEST: "TRANSFER_SEARCH_REQUEST",
  TRANSFER_SEARCH_SUCCESS: "TRANSFER_SEARCH_SUCCESS",
  TRANSFER_SEARCH_FAILURE: "TRANSFER_SEARCH_FAILURE",

  TRANSFER_BOOK_REQUEST: "TRANSFER_BOOK_REQUEST",
  TRANSFER_BOOK_SUCCESS: "TRANSFER_BOOK_SUCCESS",
  TRANSFER_BOOK_FAILURE: "TRANSFER_BOOK_FAILURE",
  TRANSFER_MY_TRIPS_SUCCESS: "TRANSFER_MY_TRIPS_SUCCESS",
  TRANSFER_MY_TRIPS_FAILURE: "TRANSFER_MY_TRIPS_FAILURE",
  TRANS_PAYLOAD_SUCCESS: "TRANS_PAYLOAD_SUCCESS",

  TRANSFER_GET_BOOKING_REQUEST: "TRANSFER_GET_BOOKING_REQUEST",
  TRANSFER_GET_BOOKING_SUCCESS: "TRANSFER_GET_BOOKING_SUCCESS",
  TRANSFER_GET_BOOKING_FAILURE: "TRANSFER_GET_BOOKING_FAILURE",

  TRANSFER_CANCEL_BOOK_REQUEST: "TRANSFER_CANCEL_BOOK_REQUEST",
  TRANSFER_CANCEL_BOOK_SUCCESS: "TRANSFER_CANCEL_BOOK_SUCCESS",
  TRANSFER_CANCEL_BOOK_FAILURE: "TRANSFER_CANCEL_BOOK_FAILURE",

  TRANSFER_FILTER_SUCCESS: "TRANSFER_FILTER_SUCCESS"
};

export default actionType;
