const actionType = {
  ENABLE_LOADING_SEARCH: "ENABLE_LOADING_SEARCH",
  DISABLE_LOADING_SEARCH: "DISABLE_LOADING_SEARCH",
  DISABLE_LOADING_GIF_SEARCH: "DISABLE_LOADING_GIF_SEARCH",
  ENABLE_LOADING_GIF_SEARCH: "ENABLE_LOADING_GIF_SEARCH",
  COUNTRYCODE_SUCCESS: "COUNTRYCODE_SUCCESS",
  COUNTRYCODE_FAILURE: "COUNTRYCODE_FAILURE",
  SELECTED_COUNTRYCODE_SUCCESS: "SELECTED_COUNTRYCODE_SUCCESS",
  USERIP_SUCCESS: 'USERIP_SUCCESS',
  USERIP_FAILURE: 'USERIP_FAILURE'
};
export default actionType;