const actionType={
    PAYMENT_SUCCESS:"PAYMENT_SUCCESS",
    PAYMENT_FAILURE:"PAYMENT_FAILURE",
    PAYMENTWITHCARD_SUCCESS:"PAYMENTWITHCARD_SUCCESS",
    PAYMENTWITHCARD_FAILURE:"PAYMENTWITHCARD_FAILURE",
    PAYLOADINFO : "PAYLOADINFO",
    // BOOKING_LOGIN_SUCCESS: "BOOKING_LOGIN_SUCCESS",
    // BOOKING_LOGIN_FAILURE: "BOOKING_LOGIN_FAILURE",
    // BOOKING_LOGOUT_SUCCESS: "BOOKING_LOGOUT_SUCCESS",
    // BOOKING_LOGOUT_FAILURE: "BOOKING_LOGOUT_FAILURE",
    // BOOKING_SIGNUP_SUCCESS: "BOOKING_SIGNUP_SUCCESS",
    // BOOKING_SIGNUP_FAILURE: "BOOKING_SIGNUP_FAILURE",
    // BOOKING_FORGETPASSWORD_SUCCESS: "BOOKING_FORGETPASSWORD_SUCCESS",
    // BOOKING_FORGETPASSWORD_FAILURE: "BOOKING_FORGETPASSWORD_FAILURE",
    // BOOKING_NEWPASSWORD_FAILURE: "BOOKING_NEWPASSWORD_FAILURE",
    // BOOKING_NEWPASSWORD_SUCCESS: "BOOKING_NEWPASSWORD_SUCCESS"
}
export default actionType