const actionType = {
CAR_FILTER_SUCCESS:"CAR_FILTER_SUCCESS",
CAR_FILTER_FAILURE:"CAR_FILTER_FAILURE",

CAR_SEARCH_SUCCESS:"CAR_SEARCH_SUCCESS",
CAR_SEARCH_FAILURE:"CAR_SEARCH_FAILURE",

CAR_LOAD_MORE_SUCCESS:"CAR_LOAD_MORE_SUCCESS",
CAR_LOAD_MORE_FAILURE:"CAR_LOAD_MORE_FAILURE",

CAR_GET_PRICE_SUCCESS:"CAR_GET_PRICE_SUCCESS",
CAR_GET_PRICE_FAILURE:"CAR_GET_PRICE_FAILURE",

CAR_BOOKING_SUCCESS:"CAR_BOOKING_SUCCESS",
CAR_BOOKING_FAILURE:"CAR_BOOKING_FAILURE",

CAR_DETAILS_FROM_DATABASE_SUCCESS:"CAR_DETAILS_FROM_DATABASE_SUCCESS",
CAR_DETAILS_FROM_DATABASE_FAILURE:"CAR_DETAILS_FROM_DATABASE_FAILURE",

CAR_BOOKING_CANCEL_SUCCESS:"CAR_BOOKING_CANCEL_SUCCESS",
CAR_BOOKING_CANCEL_FAILURE:"CAR_BOOKING_CANCEL_FAILURE",

CAR_MY_TRIPS_SUCCESS:"CAR_MY_TRIPS_SUCCESS",
CAR_MY_TRIPS_FAILURE:"CAR_MY_TRIPS_FAILURE",

PAGING_DETAILS:"PAGING_DETAILS",
DELETE_PAYMENT_PROPS:"DELETE_PAYMENT_PROPS",
CAR_PAYLOAD_SUCCESS : "CAR_PAYLOAD_SUCCESS",

CAR_EXISTS_LIST: "CAR_EXISTS_LIST"
}
export default actionType;