const actionType = {
    SHOW_IS_LOADING: "SHOW_IS_LOADING",
    HIDE_IS_LOADING: "HIDE_IS_LOADING",
    SHOW_IS_LOADING_FAILURE: "SHOW_IS_LOADING_FAILURE",
    HIDE_IS_LOADING_FAILURE: "HIDE_IS_LOADING_FAILURE",
    DISABLE_LOADING_GIF_SEARCH: "DISABLE_LOADING_GIF_SEARCH",
    ENABLE_LOADING_GIF_SEARCH: "ENABLE_LOADING_GIF_SEARCH",
     
  };
  export default actionType;