const actionType = {
  ADD_ITINERARY_SUCCESS: "ADD_ITINERARY_SUCCESS",
  ADD_ITINERARY_FAILURE: "ADD_ITINERARY_FAILURE",

  REMOVE_ITINERARY_SUCCESS: "REMOVE_ITINERARY_SUCCESS",
  REMOVE_ITINERARY_FAILURE: "REMOVE_ITINERARY_FAILURE",

  ADD_TO_WISHLIST_SUCCESS:"ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE:"ADD_TO_WISHLIST_FAILURE",

  VIEW_WISHLIST_SUCCESS:"VIEW_WISHLIST_SUCCESS",
  VIEW_WISHLIST_FAILURE:"VIEW_WISHLIST_FAILURE",

  DUMPDATA:"DUMPDATA",
  REPLACE_ITINERARY:"REPLACE_ITINERARY",

  EMAIL_DETAIL_AGENT:"EMAIL_DETAIL_AGENT",
  AGENT_MAIL_SUCCESS:"AGENT_MAIL_SUCCESS",
  AGENT_MAIL_FAILURE:"AGENT_MAIL_FAILURE"
};
export default actionType;
