const actionType = {
    ACTIVITY_SEARCH_SUCCESS: "ACTIVITY_SEARCH_SUCCESS",
    ACTIVITY_SEARCH_FAILURE: "ACTIVITY_SEARCH_FAILURE",

    ACTIVITY_INFO_REQUEST: "ACTIVITY_INFO_REQUEST",
    ACTIVITY_INFO_SUCCESS: "ACTIVITY_INFO_SUCCESS",
    ACTIVITY_INFO_FAILURE: "ACTIVITY_INFO_FAILURE",

    ACTIVITY_PRICE_REQUEST: "ACTIVITY_PRICE_REQUEST",
    ACTIVITY_PRICE_SUCCESS: "ACTIVITY_PRICE_SUCCESS",
    ACTIVITY_PRICE_FAILURE: "ACTIVITY_PRICE_FAILURE",

    ACTIVITY_CALENDER_REQUEST: "ACTIVITY_CALENDER_REQUEST",
    ACTIVITY_CALENDER_SUCCESS: "ACTIVITY_CALENDER_SUCCESS",
    ACTIVITY_CALENDER_FAILURE: "ACTIVITY_CALENDER_FAILURE",

    ACTIVITY_FILTER_SUCCESS: "ACTIVITY_FILTER_SUCCESS",
    ACTIVITY_FILTER_FAILURE: "ACTIVITY_FILTER_FAILURE",

    ACTIVITY_MYTRIP_SUCCESS: "ACTIVITY_MYTRIP_SUCCESS",
    ACTIVITY_MYTRIP_FAILURE: "ACTIVITY_MYTRIP_FAILURE",

    ACTIVITY_BOOKING_STATUS_SUCCESS: "ACTIVITY_BOOKING_STATUS_SUCCESS",
    ACTIVITY_BOOKING_STATUS_FAILURE: "ACTIVITY_BOOKING_STATUS_FAILURE",

    ACTIVITY_BOOKING_SUCCESS: "ACTIVITY_BOOKING_SUCCESS",
    ACTIVITY_BOOKING_FAILURE: "ACTIVITY_BOOKING_FAILURE",

    ACTIVITY_PAYLOAD_SUCCESS: "ACTIVITY_PAYLOAD_SUCCESS",

    ACTIVITY_LIST_HOTEL_REQUEST: "ACTIVITY_LIST_HOTEL_REQUEST",
    ACTIVITY_LIST_HOTEL_SUCCESS: "ACTIVITY_LIST_HOTEL_SUCCESS",
    ACTIVITY_LIST_HOTEL_FAILURE: "ACTIVITY_LIST_HOTEL_FAILURE",
    ACTIVITY_BOOKING_CANCELLED_SUCCESSFULLY: "ACTIVITY_BOOKING_CANCELLED_SUCCESSFULLY",
    ACTIVITY_BOOKING_CANCELLED_FAILURE: "ACTIVITY_BOOKING_CANCELLED_FAILURE",
    ACTIVITY_GET_CATEGORY_SUCCESS: "ACTIVITY_GET_CATEGORY_SUCCESS",
    ACTIVITY_GET_CATEGORY_FAILURE: "ACTIVITY_GET_CATEGORY_FAILURE",
    ACTIVITY_GET_CANCEL_SUCCESS: "ACTIVITY_GET_CANCEL_SUCCESS",
    ACTIVITY_GET_CANCEL_FAILURE: "ACTIVITY_GET_CANCEL_FAILURE",
    ACTIVITY_GET_LOCATIONS_REQUEST: "ACTIVITY_GET_LOCATIONS_REQUEST",
    ACTIVITY_GET_LOCATIONS_SUCCESS: "ACTIVITY_GET_LOCATIONS_SUCCESS",
    ACTIVITY_GET_LOCATIONS_FAILURE: "ACTIVITY_GET_LOCATIONS_FAILURE",

};
export default actionType;
