const actionTypes = {
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  TRIP_SUCCES: "TRIP_SUCCES",
  TRIP_FAILURE: "TRIP_FAILURE",
  RECENT_ACTIVITY_SUCCESS: "RECENT_ACTIVITY_SUCCESS",
  RECENT_ACTIVITY_FAILURE: "RECENT_ACTIVITY_FAILURE",
  PROFILE_IMAGE_SUCCESS: "PROFILE_IMAGE_SUCCESS",
  PROFILE_IMAGE_FAILURE: "PROFILE_IMAGE_FAILURE",
  REFUND_SUCCESS: "REFUND_SUCCESS",
  REFUND_FAILURE: "REFUND_FAILURE",
  CANCEL_ROUTE_INFO: "CANCEL_ROUTE_INFO",
  CANCELLED_SUCCESS: "CANCELLED_SUCCESS",
  CANCELLED_FAILURE: "CANCELLED_FAILURE",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE: "UPLOAD_IMAGE_FAILURE"
};
export default actionTypes;

